version: '3.8'
services:
  db:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_DB: xsync-2025
      POSTGRES_USER: xsync-2025
      POSTGRES_PASSWORD: xsync-2025
    volumes:
      - './storage/db:/var/lib/postgresql/data'
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $${POSTGRES_USER}']
      interval: 10s
      timeout: 60s
      retries: 10

  chroma:
    image: chromadb/chroma:latest
    ports:
      - "8000:8000" # Map host port 8000 to container port 8000
    volumes:
      - ./storage/chroma-data:/data # Persist data to a local directory
    environment:
      - CHROMA_SERVER_NO_AUTH=True # Disable authentication for local development
      - CHROMA_SERVER_TELEMETRY_ANALYTICS=False # Disable telemetry
